group = "com.sharmadhiraj.installed_apps"
version = "1.0-SNAPSHOT"

apply plugin: "com.android.library"
apply plugin: "kotlin-android"

android {
    namespace = "com.sharmadhiraj.installed_apps"

    compileSdk = 36

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
    }

    defaultConfig {
        minSdk = 21
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

dependencies {
    implementation "androidx.core:core-ktx:1.13.1"
}
