name: CI

on:
  pull_request:
  push:
    branches: [master, develop]

jobs:
  analyze-and-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: cd example && flutter pub get
      - run: flutter analyze
      - run: flutter test
